# ARMで動いているのかを見るシンプルなもの
name: ARMですか?
on: push

jobs:
    check-arm:
        runs-on: ubuntu-24.04-arm
        outputs:
            IS_ARM: "${{ steps.check-arm.outputs.IS_ARM }}"
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Check if ARM
              id: check-arm
              run: |
                  set -x
                  if [[ "$(uname -m)" =~ aarch64|arm64 ]]; then
                      IS_ARM="true"
                  else
                      IS_ARM="false"
                  fi
                  echo "${IS_ARM}"
                  echo "IS_ARM=$IS_ARM" >> "${GITHUB_OUTPUT}"

    disp-result:
        needs: check-arm
        runs-on: ubuntu-latest
        steps:
            - name: Display Result
              run: |
                  echo "Is this an ARM architecture? ${{ needs.check-arm.outputs.IS_ARM }}"